# -*- coding: utf-8 -*-
"""week2_medical_dialogue

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s4uvKMgFVDMhmHwjb1IlXyiH3J0lurTh
"""

"""
Week 2: Medical Dialogue Analysis using semlib
Participation Question: Do diabetes conversations mention lifestyle vs. medication?
"""

import os
import pandas as pd
import asyncio
from collections import Counter
from semlib import Session

# Get API key from environment variable
API_KEY = os.getenv("OPENAI_API_KEY")
if not API_KEY:
    raise ValueError("Please set OPENAI_API_KEY environment variable. See README for instructions.")

os.environ["OPENAI_API_KEY"] = API_KEY

# Initialize session
session = Session(model="openai/gpt-4o-mini", max_concurrency=3)

async def extract_medical_info(dialogues):
    """Extract medications, chief complaint, diabetes mention, lifestyle discussion"""

    results = await session.map(
        dialogues,
        template=lambda dialogue: f"""
        Extract the following from this medical conversation:
        1. Chief complaint (why patient came - 1 sentence)
        2. Medications mentioned (list them separated by commas, or "none")
        3. Does conversation mention diabetes? (yes/no)
        4. Does conversation mention diet, exercise, or lifestyle? (yes/no)

        Respond in this exact format:
        Chief Complaint: [answer]
        Medications: [answer]
        Diabetes: [yes/no]
        Lifestyle: [yes/no]

        Conversation:
        {dialogue}
        """.strip()
    )

    return results

def parse_extraction(text):
    """Parse the LLM response into structured data"""
    lines = text.strip().split('\n')
    data = {
        'chief_complaint': 'Not stated',
        'medications': [],
        'has_diabetes': False,
        'has_lifestyle': False
    }

    for line in lines:
        if line.startswith('Chief Complaint:'):
            data['chief_complaint'] = line.replace('Chief Complaint:', '').strip()
        elif line.startswith('Medications:'):
            meds_str = line.replace('Medications:', '').strip()
            if meds_str.lower() not in ['none', 'n/a', 'not mentioned']:
                data['medications'] = [m.strip() for m in meds_str.split(',')]
        elif line.startswith('Diabetes:'):
            data['has_diabetes'] = 'yes' in line.lower()
        elif line.startswith('Lifestyle:'):
            data['has_lifestyle'] = 'yes' in line.lower()

    return data

async def analyze_dialogues(csv_path, sample_size=1201):
    """Main analysis function"""

    print("Loading dataset...")
    df = pd.read_csv(csv_path)

    # Sample conversations
    sample_df = df.sample(n=min(sample_size, len(df)), random_state=42)
    dialogues = sample_df['dialogue'].tolist()

    print(f"Analyzing {len(dialogues)} conversations using semlib...")
    print(f"Model: {session.model}")
    print()

    # Extract information
    raw_results = await extract_medical_info(dialogues)

    # Parse results
    parsed_results = []
    all_medications = []

    diabetes_convos = 0
    diabetes_with_lifestyle = 0
    diabetes_with_meds = 0
    diabetes_with_both = 0

    for i, raw in enumerate(raw_results):
        parsed = parse_extraction(raw)
        parsed['conversation_id'] = i
        parsed_results.append(parsed)

        # Track medications
        all_medications.extend(parsed['medications'])

        # Track diabetes patterns
        if parsed['has_diabetes']:
            diabetes_convos += 1
            has_meds = len(parsed['medications']) > 0
            has_lifestyle = parsed['has_lifestyle']

            if has_meds:
                diabetes_with_meds += 1
            if has_lifestyle:
                diabetes_with_lifestyle += 1
            if has_meds and has_lifestyle:
                diabetes_with_both += 1

    # Save results
    results_df = pd.DataFrame(parsed_results)
    results_df.to_csv('week2_semlib_results.csv', index=False)

    # Print participation question answers
    print("\nPARTICIPATION QUESTION ANSWERS\n")

    print("1. Top 5 Most Mentioned Medications:")
    if all_medications:
        med_counts = Counter(all_medications)
        top_5 = med_counts.most_common(5)
        for rank, (med, count) in enumerate(top_5, 1):
            print(f"   {rank}. {med}: {count} mentions")
    else:
        print("   No medications found")

    print("\n2. Research Question:")
    print("   Do diabetes conversations mention diet, exercise, or lifestyle changes?")
    print("   What proportion discuss medication vs. lifestyle management?")

    print("\n3. Answer:")
    if diabetes_convos > 0:
        lifestyle_pct = (diabetes_with_lifestyle / diabetes_convos) * 100
        meds_pct = (diabetes_with_meds / diabetes_convos) * 100
        both_pct = (diabetes_with_both / diabetes_convos) * 100

        print(f"   Found {diabetes_convos} diabetes conversations out of {len(dialogues)}")
        print(f"\n   Diabetes conversations:")
        print(f"   - {diabetes_with_meds} ({meds_pct:.1f}%) mentioned medications")
        print(f"   - {diabetes_with_lifestyle} ({lifestyle_pct:.1f}%) mentioned lifestyle/diet/exercise")
        print(f"   - {diabetes_with_both} ({both_pct:.1f}%) mentioned both")

        if meds_pct > lifestyle_pct:
            diff = meds_pct - lifestyle_pct
            print(f"\n   Medication discussions are {diff:.1f}% more common than lifestyle discussions.")
        elif lifestyle_pct > meds_pct:
            diff = lifestyle_pct - meds_pct
            print(f"\n   Lifestyle discussions are {diff:.1f}% more common than medication discussions.")
    else:
        print(f"   No diabetes conversations found in {len(dialogues)} analyzed conversations")

    print(f"\nTotal API cost: ${session.total_cost():.3f}")
    print("Results saved to week2_semlib_results.csv\n")

    return results_df

if __name__ == "__main__":
    csv_path = "MTS-Dialog-TrainingSet.csv"

    try:
        loop = asyncio.get_running_loop()
        import nest_asyncio
        nest_asyncio.apply()
        results = asyncio.run(analyze_dialogues(csv_path, sample_size=1201))
    except RuntimeError:
        results = asyncio.run(analyze_dialogues(csv_path, sample_size=1201))